name: Build iOS App (.ipa)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x 

      - name: Install MAUI Workloads
 
        run: dotnet workload install maui

      - name: Build and Publish (.ipa)
        run: |
          cd MauiApp1
          dotnet publish -f net9.0-ios -c Release /p:ArchiveOnBuild=true /p:RuntimeIdentifier=ios-arm64 /p:CodesignKey="-" /p:CodesignProvision="-"
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-bundle
          path: MauiApp1/bin/Release/net10.0-ios/ios-arm64/publish/*.ipa
